wandb_version: 1

epochs:
  desc: null
  value: 15
batch_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: CNN
depth:
  desc: null
  value: 2
name:
  desc: null
  value: CNN SHALLOW TRAIN
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1688832215.993289
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.11.4
      5: 0.15.5
      8:
      - 1
      - 5
